{% set name = "homeassistant" %}
{% set version = "2021.12.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/homeassistant-{{ version }}.tar.gz
  sha256: ce6f1b8c5b28d73d430ceb8aa3c67f4d06cc2d0d9df4328b5d36688d27a8d1f1
  patches:
    - cryptography.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]
  skip: true  # [py>38]
  entry_points:
    - hass = homeassistant.__main__:main

requirements:
  host:
    - pip <20.3,>=8.0.3
    - python
  run:
    - aiohttp ==3.8.1
    - astral ==2.2
    - async-timeout ==4.0.0
    - attrs ==21.2.0
    - awesomeversion ==21.11.0
    - backports.zoneinfo
    - bcrypt ==3.1.7
    - certifi >=2020.12.5
    - ciso8601 ==2.2.0
    - cryptography  # ==35.0.0
    - httpx ==0.21.0
    - jinja2 ==3.0.3
    - pip <21.3,>=8.0.3
    - pyjwt ==2.1.0
    - python
    - pip <20.3,>=8.0.3
    - python-slugify ==4.0.1
    - pyyaml ==6.0
    - requests ==2.26.0
    - ruamel.yaml ==0.17.16
    - voluptuous ==0.12.2
    - voluptuous-serialize ==2.5.0
    - yarl ==1.6.3
    - ifaddr
    - atomicwrites

test:
  imports:
    - homeassistant
  commands:
    - pip check
    - hass --help
  requires:
    - pip

about:
  home: https://www.home-assistant.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Open source home automation that puts local control and privacy first.
  description: |
    Open source home automation that puts local control and privacy first.
    Powered by a worldwide community of tinkerers and DIY enthusiasts.
    Perfect to run on a Raspberry Pi or a local server.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/home-assistant/core

extra:
  recipe-maintainers:
    - jan-janssen
